services:
  - type: web
    name: user-dashboard
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/user-management-app
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
